"""Type stubs for pybind11 C++ bindings (libpromptbim)."""

__version__: str

class ComplianceEngine:
    def __init__(self) -> None: ...
    def check(self, plan_json: str, land_json: str, zoning_json: str) -> str: ...

class CostEngine:
    def __init__(self) -> None: ...
    def estimate(self, plan_json: str) -> str: ...

class MEPEngine:
    def __init__(self, grid_size: float = 0.3) -> None: ...
    def plan_mep(self, plan_json: str, config_json: str = "{}") -> str: ...

class SimulationEngine:
    def __init__(self) -> None: ...
    def generate_schedule(self, plan_json: str, total_days: int = 360) -> str: ...

class IFCGenerator:
    def __init__(self) -> None: ...
    def generate(self, plan_json: str, output_path: str) -> int: ...
    def generate_string(self, plan_json: str) -> str: ...

class USDGenerator:
    def __init__(self) -> None: ...
    def generate(self, plan_json: str, output_path: str) -> int: ...
    def generate_string(self, plan_json: str) -> str: ...

class GISEngine:
    def __init__(self) -> None: ...
    def parse_geojson(self, geojson_str: str) -> LandParcel: ...
    def parse_geojson_file(self, path: str) -> LandParcel: ...
    def parse_shapefile(self, shp_path: str) -> LandParcel: ...
    def parse_dxf(self, dxf_path: str) -> LandParcel: ...

class LandParcel:
    name: str
    area_sqm: float
    crs: str
    def __init__(self) -> None: ...
    def to_json_str(self) -> str: ...

def check_compliance(plan_json: str, land_json: str, zoning_json: str) -> str: ...
def estimate_cost(plan_json: str) -> str: ...
def plan_mep(plan_json: str, config_json: str = "{}") -> str: ...
def generate_schedule(plan_json: str, total_days: int = 360) -> str: ...
def generate_ifc(plan_json: str, output_path: str) -> int: ...
def generate_usd(plan_json: str, output_path: str) -> int: ...
def package_usdz(usd_path: str, output_path: str) -> int: ...
def parse_land_geojson(geojson_str: str) -> str: ...
def parse_land_file(path: str) -> str: ...
