"""Vertical transport components — 12 types."""

from promptbim.bim.components.base import (
    ComponentCategory,
    ComponentDef,
    PriceRange,
    SupplierInfo,
)

CAT = ComponentCategory.VERTICAL_TRANSPORT

VERTICAL_TRANSPORT_COMPONENTS = [
    ComponentDef(
        id="elevator_passenger",
        category=CAT,
        name_zh="客用電梯",
        name_en="Passenger Elevator",
        ifc_class="IfcTransportElement",
        ifc_predefined_type="ELEVATOR",
        omniclass_code="23-21 11 11",
        geometry_mode="mesh+param",
        parameters={
            "shaft_width_m": {"default": 2.1, "min": 1.6, "max": 3.0},
            "shaft_depth_m": {"default": 2.4, "min": 1.8, "max": 3.5},
            "door_width_m": {"default": 0.9, "min": 0.8, "max": 1.4},
            "capacity_kg": {"default": 1000, "min": 450, "max": 2500},
            "speed_mps": {"default": 1.0, "min": 0.5, "max": 6.0},
            "stops": {"default": 5, "min": 2, "max": 50},
        },
        suppliers=[
            SupplierInfo(
                name="永大電機",
                brand="YUNGTAY",
                model_number="YHP",
                catalog_url="https://www.yungtay.com",
                country="TW",
                price=PriceRange(
                    min_price=1500000,
                    max_price=2800000,
                    unit="per_unit",
                    source="台灣市場參考價 2025",
                ),
            ),
            SupplierInfo(
                name="OTIS",
                brand="OTIS",
                model_number="Gen2 Comfort",
                catalog_url="https://www.otis.com",
                country="US",
                price=PriceRange(
                    min_price=2500000,
                    max_price=4500000,
                    unit="per_unit",
                    source="台灣代理商參考價 2025",
                ),
            ),
            SupplierInfo(
                name="KONE",
                brand="KONE",
                model_number="MonoSpace 500",
                catalog_url="https://www.kone.com",
                country="FI",
                price=PriceRange(
                    min_price=2200000,
                    max_price=4000000,
                    unit="per_unit",
                    source="台灣代理商參考價 2025",
                ),
            ),
            SupplierInfo(
                name="Schindler",
                brand="Schindler",
                model_number="3300AP",
                country="CH",
                price=PriceRange(
                    min_price=2000000,
                    max_price=3800000,
                    unit="per_unit",
                    source="台灣代理商參考價 2025",
                ),
            ),
            SupplierInfo(
                name="三菱電機",
                brand="MITSUBISHI",
                model_number="NEXIEZ-LITE",
                country="JP",
                price=PriceRange(
                    min_price=2000000,
                    max_price=3600000,
                    unit="per_unit",
                    source="台灣代理商參考價 2025",
                ),
            ),
            SupplierInfo(
                name="日立",
                brand="HITACHI",
                model_number="Standard-III",
                country="JP",
                price=PriceRange(
                    min_price=1900000,
                    max_price=3400000,
                    unit="per_unit",
                    source="台灣代理商參考價 2025",
                ),
            ),
            SupplierInfo(
                name="蒂森克虜伯",
                brand="TK Elevator",
                model_number="Synergy 300",
                country="DE",
                price=PriceRange(
                    min_price=1800000,
                    max_price=3500000,
                    unit="per_unit",
                    source="台灣代理商參考價 2025",
                ),
            ),
        ],
        ai_keywords=["電梯", "升降機", "客梯", "elevator", "lift", "passenger lift"],
        ai_placement_rules="需獨立電梯井道。通常位於建築核心筒。每棟至少1台，8層以上強制。無障礙電梯至少1台。",
    ),
    ComponentDef(
        id="elevator_freight",
        category=CAT,
        name_zh="貨梯",
        name_en="Freight Elevator",
        ifc_class="IfcTransportElement",
        ifc_predefined_type="ELEVATOR",
        geometry_mode="mesh+param",
        parameters={
            "shaft_width_m": {"default": 2.5, "min": 2.0, "max": 4.0},
            "shaft_depth_m": {"default": 3.0, "min": 2.0, "max": 5.0},
            "capacity_kg": {"default": 2000, "min": 1000, "max": 5000},
        },
        ai_keywords=["貨梯", "freight elevator", "cargo lift", "貨用電梯"],
        ai_placement_rules="服務區/地下室出入口旁。門寬>=1.4m。",
    ),
    ComponentDef(
        id="elevator_service",
        category=CAT,
        name_zh="服務電梯",
        name_en="Service Elevator",
        ifc_class="IfcTransportElement",
        ifc_predefined_type="ELEVATOR",
        geometry_mode="mesh+param",
        parameters={
            "shaft_width_m": {"default": 2.1, "min": 1.8, "max": 3.0},
            "shaft_depth_m": {"default": 2.4, "min": 2.0, "max": 3.0},
            "capacity_kg": {"default": 1350, "min": 800, "max": 2000},
        },
        ai_keywords=["服務電梯", "service elevator", "後勤電梯"],
        ai_placement_rules="後勤區域，供清潔、維護人員使用。",
    ),
    ComponentDef(
        id="escalator_30deg",
        category=CAT,
        name_zh="電扶梯(30°)",
        name_en="Escalator 30°",
        ifc_class="IfcTransportElement",
        ifc_predefined_type="ESCALATOR",
        geometry_mode="mesh+param",
        parameters={
            "width_m": {"default": 1.0, "options": [0.6, 0.8, 1.0]},
            "rise_m": {"default": 4.5, "min": 3.0, "max": 6.0},
            "speed_mps": {"default": 0.5, "min": 0.3, "max": 0.65},
        },
        suppliers=[
            SupplierInfo(
                name="KONE",
                brand="KONE",
                model_number="TransitMaster 140",
                country="FI",
                price=PriceRange(
                    min_price=3500000,
                    max_price=6000000,
                    unit="per_unit",
                    source="台灣代理商參考價 2025",
                ),
            ),
            SupplierInfo(
                name="Schindler",
                brand="Schindler",
                model_number="9300AE",
                country="CH",
                price=PriceRange(
                    min_price=3000000,
                    max_price=5500000,
                    unit="per_unit",
                    source="台灣代理商參考價 2025",
                ),
            ),
            SupplierInfo(
                name="OTIS",
                brand="OTIS",
                model_number="506NCE",
                country="US",
                price=PriceRange(
                    min_price=3200000,
                    max_price=5800000,
                    unit="per_unit",
                    source="台灣代理商參考價 2025",
                ),
            ),
            SupplierInfo(
                name="三菱電機",
                brand="MITSUBISHI",
                model_number="Series-Z",
                country="JP",
                price=PriceRange(
                    min_price=3000000,
                    max_price=5200000,
                    unit="per_unit",
                    source="台灣代理商參考價 2025",
                ),
            ),
        ],
        ai_keywords=["電扶梯", "escalator", "手扶梯"],
        ai_placement_rules="商場/捷運站，成對配置（上下行）。30°為標準傾斜角。",
    ),
    ComponentDef(
        id="escalator_35deg",
        category=CAT,
        name_zh="電扶梯(35°)",
        name_en="Escalator 35°",
        ifc_class="IfcTransportElement",
        ifc_predefined_type="ESCALATOR",
        geometry_mode="mesh+param",
        parameters={
            "width_m": {"default": 1.0, "options": [0.6, 0.8, 1.0]},
            "rise_m": {"default": 4.5, "min": 3.0, "max": 6.0},
        },
        ai_keywords=["電扶梯35", "escalator 35", "steep escalator"],
        ai_placement_rules="空間有限時使用35°角，水平距離較短。",
    ),
    ComponentDef(
        id="moving_walkway",
        category=CAT,
        name_zh="電動步道",
        name_en="Moving Walkway",
        ifc_class="IfcTransportElement",
        ifc_predefined_type="MOVINGWALKWAY",
        geometry_mode="mesh+param",
        parameters={
            "width_m": {"default": 1.0, "options": [0.8, 1.0, 1.4]},
            "length_m": {"default": 20.0, "min": 5.0, "max": 100.0},
        },
        ai_keywords=["電動步道", "moving walkway", "travelator", "自動步道"],
        ai_placement_rules="機場、大型商場水平輸送。長度>50m時建議設置。",
    ),
    ComponentDef(
        id="stair_straight",
        category=CAT,
        name_zh="直跑樓梯",
        name_en="Straight Stair",
        ifc_class="IfcStair",
        ifc_predefined_type="STRAIGHT_RUN_STAIR",
        parameters={
            "width_m": {"default": 1.2, "min": 0.75, "max": 2.0},
            "riser_height_m": {"default": 0.17, "min": 0.14, "max": 0.20},
            "tread_depth_m": {"default": 0.27, "min": 0.24, "max": 0.30},
            "rise_m": {"default": 3.0, "min": 2.5, "max": 4.5},
        },
        ai_keywords=["直跑樓梯", "straight stair", "直梯"],
        ai_placement_rules="最簡單形式。安全梯淨寬>=1.2m（台灣法規）。",
    ),
    ComponentDef(
        id="stair_l_shaped",
        category=CAT,
        name_zh="L型樓梯",
        name_en="L-Shaped Stair",
        ifc_class="IfcStair",
        ifc_predefined_type="QUARTER_TURN_STAIR",
        parameters={
            "width_m": {"default": 1.2, "min": 0.9, "max": 1.8},
            "rise_m": {"default": 3.0, "min": 2.5, "max": 4.5},
            "landing_length_m": {"default": 1.2, "min": 1.0, "max": 2.0},
        },
        ai_keywords=["L型樓梯", "L-shaped stair", "quarter turn stair", "轉角樓梯"],
        ai_placement_rules="轉90°，中間設平台。適合角落空間。",
    ),
    ComponentDef(
        id="stair_u_shaped",
        category=CAT,
        name_zh="U型樓梯",
        name_en="U-Shaped Stair",
        ifc_class="IfcStair",
        ifc_predefined_type="HALF_TURN_STAIR",
        parameters={
            "width_m": {"default": 1.2, "min": 0.9, "max": 1.8},
            "rise_m": {"default": 3.0, "min": 2.5, "max": 4.5},
        },
        ai_keywords=["U型樓梯", "U-shaped stair", "half turn stair", "折返梯"],
        ai_placement_rules="最常見安全梯形式。折返設計節省空間。",
    ),
    ComponentDef(
        id="stair_spiral",
        category=CAT,
        name_zh="旋轉樓梯",
        name_en="Spiral Stair",
        ifc_class="IfcStair",
        ifc_predefined_type="SPIRAL_STAIR",
        parameters={
            "outer_radius_m": {"default": 1.5, "min": 0.8, "max": 3.0},
            "rise_m": {"default": 3.0, "min": 2.5, "max": 4.5},
        },
        ai_keywords=["旋轉樓梯", "螺旋梯", "spiral stair", "circular stair"],
        ai_placement_rules="裝飾性或空間極小處。不可作為安全梯（台灣法規）。",
    ),
    ComponentDef(
        id="ramp_straight",
        category=CAT,
        name_zh="直線坡道",
        name_en="Straight Ramp",
        ifc_class="IfcRamp",
        ifc_predefined_type="STRAIGHT_RUN_RAMP",
        parameters={
            "width_m": {"default": 1.5, "min": 0.9, "max": 3.0},
            "slope_percent": {"default": 8.3, "min": 5.0, "max": 12.5},
            "rise_m": {"default": 0.75, "min": 0.1, "max": 1.0},
        },
        ai_keywords=["坡道", "ramp", "斜坡", "無障礙坡道"],
        ai_placement_rules="無障礙通道必設。坡度<=1/12（8.3%），每段高差<=75cm。",
    ),
    ComponentDef(
        id="ramp_curved",
        category=CAT,
        name_zh="弧形坡道",
        name_en="Curved Ramp",
        ifc_class="IfcRamp",
        parameters={
            "width_m": {"default": 3.5, "min": 2.5, "max": 7.0},
            "inner_radius_m": {"default": 5.0, "min": 3.0, "max": 15.0},
            "slope_percent": {"default": 8.3, "max": 12.5},
        },
        ai_keywords=["弧形坡道", "curved ramp", "螺旋坡道", "車道"],
        ai_placement_rules="地下停車場車道常用。內圈半徑>=5m。",
    ),
]
